### ISSUE TITLE
Enable to use it with OpenAPI 3.0

### ISSUE THREAD

**Issue by sotayamashita** [sotayamashita/apivore#1]
## TODO (Order of priority)

- [x] Understand how it works. 
- [x] Commit OpenAPI3.0 specification.
   - [googleapis/gnostic](https://github.com/googleapis/gnostic/blob/master/OpenAPIv3/openapi-3.0.json)
- [ ] Enable to load file from local.
- [ ] Enable to use the format with Yaml and JSON.
- [ ] Update rspec
- [ ] Setup TravisCI, dependabot and Codecov
- [ ] Add an appropriate license.
- [ ] Add a comment to the https://github.com/westfieldlabs/apivore/issues/113
- [ ] Add `## Installation` section to `README.md`.
- [ ] Add `## Usage` section for `[:get, :post, :put, :patch, :delete]` to `README.md`.
- [ ] Add `## RoR support version` section to `README.md`
   - [ ok ] Rails 5.2 
- [ ] Merge https://github.com/westfieldlabs/apivore/pull/117 into `feature/openapi-v3`
  - Keep effort commit info
- [ ] Add a post which describe how to add an appropriate license for Apache2.0. 

## Memo

```diff
gem "rspec-rails"
+ gem 'apivore',  github: "sotayamashita/apivore"
```

## Troubleshooting

```
ActionController::UnknownFormat:
```
↓
```ruby
# in one controller
class API::ApplicationController
    before_action :set_default_response_format
    def set_default_response_format
        request.format = :json
    end
```

or 

```ruby
# in rspec
it { expect(subject).to validate(:get, "~/", 200, {"_header": "Content-Type: application/json"}) }
```

## References

- https://tech.recruit-mp.co.jp/server-side/top-down-swagger/
- https://qiita.com/kymmt90/items/26c493e5f751a7e4f946
- https://qiita.com/tmpyn/items/72adfcc244caffc5a6e7
